_target_: orchestrator.config.SystemConfig
model_name: gpt-3.5-turbo

model_auth:
  url:
  api_key:

model_params:
  temperature: 0
  max_tokens: 512


vectorstore: chromadb

rag_params:
  top_k_retrieval: 5

